config/routes.rb
Rails.application.routes.draw do
  root to: 'cocktails#index'

  resources :cocktails, only: [:index, :show, :new, :create] do
    resources :doses, only: [:new, :create, :destroy]
  end
end

app/models/cocktail.rb
class Cocktail < ActiveRecord::Base
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }

  validates_presence_of :name, :image
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/models/dose.rb
class Dose < ActiveRecord::Base
  belongs_to :cocktail
  belongs_to :ingredient

  validates_presence_of :amount, :cocktail, :ingredient
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  has_many :doses, dependent: :destroy
  has_many :cocktails, through: :doses

  validates_presence_of :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController

  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name, :image)
  end

end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  before_action :get_cocktail

  def new
    @ingredients = Ingredient.all
    @dose = Dose.new(cocktail: @cocktail)
  end

  def create
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail

    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

private

  def dose_params
    params.require(:dose).permit(:amount, :ingredient_id)
  end

  def get_cocktail
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cocktails/index.html.erb
<h2>Liste de cocktails <%= link_to 'ajouter', new_cocktail_path %></h2>

<ul>
  <% @cocktails.each do |cocktail| %>
    <li><%= link_to cocktail.name, cocktail_path(cocktail) %></li>
  <% end %>
</ul>

app/views/cocktails/new.html.erb
<h2>Ajouter un nouveau Cocktail</h2>

<%= simple_form_for(@cocktail, html: { multipart: true }) do |f| %>
  <%= f.input :name %><br />
  <%= f.input :image %>

  <%= f.submit %>
<% end %>

app/views/cocktails/show.html.erb
<h2><%= @cocktail.name %></h2>

<%= image_tag @cocktail.image.url(:medium) %>

<ul>
  <% @cocktail.doses.each do |dose| %>
    <li><%= "#{dose.amount} #{dose.ingredient.name}" %></li>
  <% end %>
</ul>

<%= link_to 'Ajouter un ingredient', new_cocktail_dose_path(@cocktail)  %>

<%= link_to 'Revenir à la liste', cocktails_path  %>

app/views/doses/new.html.erb
<h2>Ajouter un ingrédient pour <%= link_to @cocktail.name, cocktail_path(@cocktail) %></h2>

<%= simple_form_for(@dose, url: cocktail_doses_path) do |f| %>
  <%= f.input :amount %>
  <%= f.input :ingredient_id, collection: @ingredients %>

  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MisterCocktail</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>